<?php
namespace SclZfCart\View\Helper;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-02-16 at 14:18:26.
 */
class CartTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Cart
     */
    protected $object;

    /**
     * @var \Zend\ServiceManager\ServiceLocatorInterface
     */
    protected $serviceLocator;

    /**
     * @var \Zend\View\HelperPluginManager
     */
    protected $helperPluginManager;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->serviceLocator = $this->getMock('Zend\ServiceManager\ServiceLocatorInterface');
        $this->helperPluginManager = $this->getMockBuilder('Zend\View\HelperPluginManager')
            ->disableOriginalConstructor()
            ->getMock();

        $this->object = new Cart;
    }

    /**
     * @covers SclZfCart\View\Helper\Cart::setServiceLocator
     * @covers SclZfCart\View\Helper\Cart::getServiceLocator
     * @covers SclZfCart\View\Helper\Cart::__invoke
     * @todo   Implement test__invoke().
     */
    public function test__invoke()
    {
        $cart = 'TestCartObject';

        $this->helperPluginManager->expects($this->once())
            ->method('getServiceLocator')
            ->will($this->returnValue($this->serviceLocator));

        $this->serviceLocator->expects($this->once())
            ->method('get')
            ->with($this->equalTo('SclZfCart\Cart'))
            ->will($this->returnValue($cart));

        $this->object->setServiceLocator($this->helperPluginManager);

        $this->assertEquals($cart, $this->object->__invoke(), 'Expected cart value does not match returned value');
    }
}
