<?php

namespace SclZfCartTests\Entity;

use SclZfCart\Entity\Cart;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-02-08 at 17:05:29.
 */
class CartTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Cart
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Cart;
    }

    protected function fluentGetSetTest($name, $value)
    {
        $setter = 'set' . $name;
        $getter = 'get' . $name;

        $result = $this->object->$setter($value);

        $this->assertNull($result, "set$name returned a value.");

        $result = $this->object->$getter();

        $this->assertEquals($value, $result, "get$name didn't return the value set.");

        return $this;
    }

    /**
     */
    public function testEntity()
    {
        $this->assertInstanceOf(
            'SclZfCart\Entity\CartInterface',
            $this->object,
            'CartItem is not an instance of SclZfCartEntity\CartInterface'
        );

        $this->fluentGetSetTest('id', 34)
             ->fluentGetSetTest('lastUpdated', new \DateTime());
    }
}
