<?php

namespace SclZfCartTests\Entity;

use SclZfCart\Entity\DoctrineCartItem;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-02-08 at 17:05:29.
 */
class DoctrineCartItemTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var CartItem
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new DoctrineCartItem;
    }

    protected function fluentGetSetTest($name, $value)
    {
        $setter = 'set' . $name;
        $getter = 'get' . $name;

        $result = $this->object->$setter($value);

        $this->assertEquals($this->object, $result, "set$name doesn't return itself.");

        $result = $this->object->$getter();

        $this->assertEquals($value, $result, "get$name didn't return the value set.");

        return $this;
    }

    /**
     */
    public function testEntity()
    {
        $this->assertInstanceOf(
            'SclZfCart\Entity\CartItemInterface',
            $this->object,
            'DoctrineCartItem is not an instance of SclZfCartEntity\CartItemInterface'
        );

        $this->fluentGetSetTest('id', 23)
             ->fluentGetSetTest('cart', $this->getMock('SclZfCart\Entity\CartInterface'))
             ->fluentGetSetTest('uid', uniqid())
             ->fluentGetSetTest('type', 'random_type')
             ->fluentGetSetTest('data', 'random data string');
    }
}
