<?php

namespace SclZfCartTests\Entity;

use SclZfCart\Entity\DoctrineCart;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-02-08 at 17:05:29.
 */
class DoctrineCartTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Cart
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new DoctrineCart;
    }

    protected function fluentGetSetTest($name, $value)
    {
        $setter = 'set' . $name;
        $getter = 'get' . $name;

        $result = $this->object->$setter($value);

        $this->assertEquals($this->object, $result, "set$name doesn't return itself.");

        $result = $this->object->$getter();

        $this->assertEquals($value, $result, "get$name didn't return the value set.");

        return $this;
    }

    /**
     */
    public function testEntity()
    {
        $this->assertInstanceOf(
            'SclZfCart\Entity\CartInterface',
            $this->object,
            'DoctrineCartItem is not an instance of SclZfCartEntity\CartInterface'
        );

        $this->fluentGetSetTest('id', 34)
             ->fluentGetSetTest('lastUpdated', new \DateTime());
    }

    public function testItems()
    {
        $this->markTestIncomplete('write this test');
    }
}
