language: php

php:
  - 5.4
  - 5.5

before_script:
  - composer self-update
  - composer install --dev --prefer-source
  - mkdir -p build/logs

script:
  - vendor/bin/phpspec run -n
  - vendor/bin/phpcs --standard=psr2 src
  - vendor/bin/phpmd src text codesize

after_script:
  - php vendor/bin/coveralls -v
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
