<?php
namespace SclZfCart\Storage;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-02-08 at 17:05:30.
 */
class CartItemSerializerTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var CartItemSerializer
     */
    protected $serializer;

    /**
     */
    protected function setUp()
    {
        $this->serializer = new CartItemSerializer;
    }

    /**
     * @covers SclZfCart\Storage\CartItemSerializer::serialize
     * @covers SclZfCart\Storage\CartItemSerializer::unserialize
     */
    public function testSerialize()
    {
        $item = $this->getMock('SclZfCart\CartItemInterface');

        $serialized = $this->serializer->serialize($item);

        $this->assertInternalType('string', $serialized);
        $this->assertGreaterThan(0, strlen($serialized));

        $unserialized = $this->serializer->unserialize($serialized);

        $this->assertEquals($item, $unserialized);
    }

    /**
     * @covers SclZfCart\Storage\CartItemSerializer::unserialize
     * @expectedException SclZfCart\Exception\InvalidArgumentException
     */
    public function testSerializedData()
    {
        $serialized = 'broken data';

        $this->serializer->unserialize($serialized, 'Bad data test');

        $serialized = serialize(new \stdClass());

        $this->serializer->unserialize($serialized, 'Bad object test');
    }
}
