<?php
namespace SclZfCart\Listener;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-02-16 at 14:18:26.
 */
class CartListenerTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var CartListener
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new CartListener;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers SclZfCart\Listener\CartListener::completeOrder
     * @todo   Implement testCompleteOrder().
     */
    public function testCompleteOrder()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
