<?php
$this->headLink()->appendStylesheet($this->basePath() . '/css/scl-zf-cart/cart.css');

$form = $this->form;
$cart = $this->getCart();

echo $this->pageTitle('Checkout Confirmation');
?>
<p>Please review you order details before completing payment.</p>
<table class="table">
    <thead>
        <tr>
            <th>Description</th>
            <th>Quantity</th>
            <th>Tax</th>
            <th>Price</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($cart->getItems() as $item) : ?>
            <tr>
                <td>
                    <?php echo $this->escapeHtml($item->getTitle()); ?><br>
                    <em><?php echo $this->escapeHtml($item->getDescription()); ?></em>
                </td>
                <td><a href="<?php echo $this->url('cart'); ?>" rel="tooltip" title="Click to change quantity"><?php echo $item->getQuantity(); ?></a></td>
                <td><?php echo $this->formatMoney($item->getPrice()->getTax()); ?></td>
                <td><?php echo $this->formatMoney($item->getPrice()->getAmount()); ?></td>
            </tr>
        <?php endforeach; ?>
    </tbody>
    <tfoot>
        <tr>
            <td></td>
            <th>Sub Total:</th>
            <td><?php echo $this->formatMoney($cart->getTotal()->getTax()); ?></td>
            <td><?php echo $this->formatMoney($cart->getTotal()->getAmount()); ?></td>
        </tr>
        <tr>
            <td></td>
            <th>Total:</th>
            <td></td>
            <td><?php echo $this->formatMoney($cart->getTotal()->getTotal()); ?></td>
        </tr>
    </tfoot>
</table>

<?php
$form->prepare();
echo $this->form()->openTag($form);
echo $this->formCollection($form);
echo $this->form()->closeTag($form);
?>

<div class="clear"></div>
