<?php echo $this->pageTitle('View Cart'); ?>

<table class="table">
    <thead>
        <tr>
            <th></th>
            <th>Description</th>
            <th>Quantity</th>
            <th>Price</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($cart->getItems() as $item) : ?>
            <tr>
                <td>X</td>
                <td>
                    <?php echo $this->escapeHtml($item->getTitle()); ?><br>
                    <small><?php echo $this->escapeHtml($item->getDescription()); ?></small>
                </td>
                <td><?php echo $item->getQuantity(); ?></td>
                <td></td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>