<?php $form = $this->form; ?>
<?php echo $this->pageTitle('Checkout Confirmation'); ?>

<p>Please review you order details before completing payment.</p>
<table class="table">
    <thead>
        <tr>
            <th>Description</th>
            <th>Quantity</th>
            <th>Price</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->getCart()->getItems() as $item) : ?>
            <tr>
                <td>
                    <?php echo $this->escapeHtml($item->getTitle()); ?><br>
                    <em><?php echo $this->escapeHtml($item->getDescription()); ?></em>
                </td>
                <td><a href="<?php echo $this->url('cart'); ?>" rel="tooltip" title="Click to change quantity"><?php echo $item->getQuantity(); ?></a></td>
                <td><?php echo $this->formatPrice(0); ?></td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<?php
$form->prepare();
echo $this->form()->openTag($form);
echo $this->formCollection($form);
echo $this->form()->closeTag($form);
?>

<div class="clear"></div>
