<?php
namespace SclZfCart;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-02-16 at 14:18:26.
 */
class CartEventTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var CartEvent
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new CartEvent;
    }

    /**
     * @covers SclZfCart\CartEvent::setRoute
     * @covers SclZfCart\CartEvent::getRoute
     */
    public function testGetSetRoute()
    {
        $route = new \SclZfUtilities\Model\Route('test/route', array('a' => 'xyz'));

        $this->object->setRoute($route);

        $this->assertEquals($route, $this->object->getRoute());
    }

    /**
     * @covers SclZfCart\CartEvent::getCart
     */
    public function testGetCartWithNoCartParam()
    {
        $this->assertNull($this->object->getCart());
    }

    /**
     * @covers SclZfCart\CartEvent::getCart
     * @expectedException \SclZfCart\Exception\InvalidArgumentException
     */
    public function testGetCartWithBadCartParam()
    {
        $this->object->setParam(CartEvent::PARAM_CART, 'xyz');
        $this->assertNull($this->object->getCart());
    }

    /**
     * @covers SclZfCart\CartEvent::getCart
     */
    public function testGetCartWithGoodCartParam()
    {
        $cart = $this->getMock('SclZfCart\Cart');
        $this->object->setParam(CartEvent::PARAM_CART, $cart);
        
        $this->assertEquals($cart, $this->object->getCart());
    }
}
