<?php
$form = $this->form;
$cart = $this->cart;
echo $this->pageTitle('View Cart');

$this->headLink()->appendStylesheet($this->basePath() . '/css/scl-zf-cart/cart.css');

$form->prepare();
$form->setAttribute('action', $this->url('cart'));
?>
<?php echo $this->form()->openTag($form); ?>
    <table class="table">
        <thead>
            <tr>
                <th></th>
                <th>Description</th>
                <th>Quantity</th>
                <th>Tax</th>
                <th>Price</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($cart->getItems() as $item) : ?>
                <tr>
                    <td><a href="<?php echo $this->url('cart/remove', array('item' => $item->getUid())); ?>" rel="tooltip" title="Removed item from the cart">X</a></td>
                    <td>
                        <?php echo $this->escapeHtml($item->getTitle()); ?><br>
                        <small><?php echo $this->escapeHtml($item->getDescription()); ?></small>
                    </td>
                    <td><?php
                        $quantity = $form->getQuantityElement($item);
                        echo is_scalar($quantity)
                            ? $this->escapeHtml($quantity)
                            : $this->formElement($quantity);
                    ?></td>
                    <td><?php echo $this->formatMoney($item->getPrice()->getTax()); ?></td>
                    <td><?php echo $this->formatMoney($item->getPrice()->getAmount()); ?></td>
                </tr>
            <?php endforeach; ?>
        </tbody>
        <tfoot>
            <tr>
                <td colspan="2"></td>
                <th>Sub Total:</th>
                <td><?php echo $this->formatMoney($cart->getTotal()->getTax()); ?></td>
                <td><?php echo $this->formatMoney($cart->getTotal()->getAmount()); ?></td>
            </tr>
            <tr>
                <td colspan="2"></td>
                <th>Total:</th>
                <td></td>
                <td><?php echo $this->formatMoney($cart->getTotal()->getTotal()); ?></td>
            </tr>
        </tfoot>
    </table>

    <?php echo $this->formInput($form->get('checkout')); ?>
    <?php echo $this->formInput($form->get('update')); ?>

    <div class="clear"></div>
<?php echo $this->form()->closeTag($form); ?>
